### ISSUE TITLE
Wrong logic in the script

### ISSUE THREAD

**Issue by peeech** [Holo-Host/hpos-configure-holochain#38]
Currently there are flaws in the logic that script is executing:
- [ ] different agent is created for each installed dna [here](https://github.com/Holo-Host/hpos-configure-holochain/blob/ac1166f8861d33f2673386ca64a26282ddeebe88/src/lib.rs#L43), while there should be only one agent created during entire process
- [ ] interface is attached with each call of `install_happ` [here](https://github.com/Holo-Host/hpos-configure-holochain/blob/ac1166f8861d33f2673386ca64a26282ddeebe88/src/websocket.rs#L58) while it should be done only once during entire script. It has already been fixed in [this commit](https://github.com/Holo-Host/hpos-configure-holochain/pull/3/commits/45f4593e051eebdb55b3d41676b54814ee2e60c0) on never merged PR #3

**Comment by zippy** [comment]
@Br1ght0ne please note that the correct logic is mostly implemented here: 
https://github.com/Holo-Host/hpos-configure-holochain/pull/3

**Comment by peeech** [comment]
fixed in #57
