### ISSUE TITLE
after deactivation of an app its `app_id` is banned for ever

### ISSUE THREAD

**Issue by peeech** [Holo-Host/hpos-configure-holochain#59]
Let's take app with `app_id`. Let's say it gets installed and then removed. The process looks like this:
- install app with `app_id` -> app-state=(installed, inactive)
- activate app with `app_id` -> app-state=(installed, active)
- deactivate app with `app_id` -> app-state=(installed, inactive)

Any future attempt of installation of `app_id` will result in an error `AppAlreadyInstalled("app_id")` and app installation will be terminated without activation of an app.

**Comment by zippy** [comment]
So we could just look for that case and active the app if it has the same agentkey, but this is fine for now.

**Comment by alastairong** [comment]
@zippy @peeech Is this issue fixed now?

**Comment by peeech** [comment]
Closing as stale
